CREATE TABLE resume
(
    uuid      CHAR(36) primary key not null,
    full_name VARCHAR              not null
);

CREATE TABLE contact
(
    id          bigint generated by default as identity primary key,
    resume_uuid char(36) not null references resume (uuid) on delete cascade,
    type        VARCHAR  not null,
    value       VARCHAR  not null
);

create unique index contact_uuid_type_index
    on contact (resume_uuid, type);

CREATE TABLE section
(
    id          int generated by default as identity primary key,
    resume_uuid char(36) not null references resume (uuid) on delete cascade,
    type        VARCHAR  not null,
    value       VARCHAR  not null
);

create unique index list_section_uuid_index
    on section (resume_uuid, type);